# Generated by Django 2.2.2 on 2019-10-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('fileurl', models.CharField(max_length=500)),
                ('fcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='studentstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susername', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('fcount', models.IntegerField(default=0)),
            ],
        ),
    ]
