# Generated by Django 2.2.2 on 2019-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_filedb_studentstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('credits1', models.CharField(max_length=10)),
                ('coordinator', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='filedb',
            name='courseid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedb',
            name='filecontent',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentstats',
            name='courseid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
