# Generated by Django 2.2.2 on 2019-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_auto_20191101_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
